# Generated by Django 5.2.7 on 2025-10-24 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_zkpasswordresettoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_service_data', models.TextField()),
                ('shared_identity_level', models.IntegerField(default=0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_permissions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_services', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Connected Service',
                'verbose_name_plural': 'Connected Services',
                'db_table': 'connected_services',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('identity_upgrade', 'Identity Level Upgraded'), ('identity_downgrade', 'Identity Level Downgraded'), ('service_connected', 'Service Connected'), ('service_revoked', 'Service Revoked'), ('data_export', 'Data Exported'), ('account_settings', 'Account Settings Changed')], max_length=50)),
                ('encrypted_details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'db_table': 'security_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIdentityLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_level', models.IntegerField(choices=[(0, 'Anonymous'), (1, 'Basic Verified'), (2, 'Government ID Verified'), (3, 'Professionally Verified')], default=0)),
                ('encrypted_verification_data', models.TextField(blank=True, null=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('govt_id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('professional_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_level', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'User Identity Level',
                'verbose_name_plural': 'User Identity Levels',
                'db_table': 'user_identity_levels',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_preferences', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
