# Generated by Django 5.2.8 on 2025-11-29 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_zktwofactorloginsession'),
        ('svasetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='log_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Changed'), ('identity_upgrade', 'Identity Level Upgraded'), ('identity_downgrade', 'Identity Level Downgraded'), ('service_connected', 'Service Connected'), ('service_revoked', 'Service Revoked'), ('app_connected', 'App Connected'), ('app_revoked', 'App Access Revoked'), ('app_scopes_updated', 'App Scopes Updated'), ('data_export', 'Data Exported'), ('account_settings', 'Account Settings Changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, help_text='OAuth app client_id', max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('app_logo', models.URLField(blank=True, null=True)),
                ('app_description', models.TextField(blank=True, null=True)),
                ('approved_scopes', models.JSONField(default=list, help_text='List of scopes user has approved')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_scope_update', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_connections', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'User App Connection',
                'verbose_name_plural': 'User App Connections',
                'db_table': 'user_app_connections',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_app_co_user_id_565224_idx'), models.Index(fields=['client_id', 'is_active'], name='user_app_co_client__914f6f_idx')],
                'unique_together': {('user', 'client_id')},
            },
        ),
    ]
