# Generated by Django 5.2.8 on 2026-02-06 09:45

import svasetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svasetting', '0002_connectedservice_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedservice',
            name='verification_token',
            field=models.CharField(db_index=True, default=svasetting.models._default_verification_token, editable=False, max_length=64, unique=True),
        ),
    ]
