# Generated by Django 5.2.8 on 2025-11-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svasetting', '0002_alter_securitylog_log_type_userappconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappconnection',
            name='encrypted_sharing_blob',
            field=models.TextField(blank=True, help_text='Pre-encrypted sharing data blob for instant access', null=True),
        ),
        migrations.AddField(
            model_name='userappconnection',
            name='sharing_blob_encrypted_at',
            field=models.DateTimeField(blank=True, help_text='When the sharing blob was last encrypted/updated', null=True),
        ),
    ]
