# Generated by Django 5.2.8 on 2025-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svasetting', '0003_userappconnection_encrypted_sharing_blob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappconnection',
            name='sharing_blob_salt',
            field=models.TextField(blank=True, help_text='Salt for decrypting the sharing blob (base64 encoded)', null=True),
        ),
    ]
