#!/bin/bash
# Azure App Service startup script
# This script runs collectstatic and then starts gunicorn

# Collect static files
python manage.py collectstatic --noinput

# Start gunicorn (Oryx will handle this, but we can also do it explicitly)
# The actual command will be generated by Oryx, but this ensures collectstatic runs first
exec "$@"

