# Generated by Django 5.2.8 on 2026-02-05 05:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZKEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('encrypted_data', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('auth_proof', models.CharField(max_length=255)),
                ('username_hash', models.CharField(max_length=64)),
                ('device_fingerprint', models.CharField(blank=True, help_text='SHA-256 hash of device fingerprint for registration', max_length=64, null=True)),
                ('passkey_credential_id', models.CharField(blank=True, max_length=512, null=True)),
                ('passkey_public_key', models.TextField(blank=True, null=True)),
                ('use_both_methods', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'zk_email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_data', models.TextField(help_text='AES-256-GCM encrypted waitlist data (base64)')),
                ('salt', models.CharField(help_text='Cryptographic salt for key derivation (base64)', max_length=255)),
                ('email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of email for duplicate checking', max_length=64)),
                ('consent_to_updates', models.BooleanField(default=True, help_text='Whether user consented to receive updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'db_table': 'waitlist_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_hash'], name='waitlist_en_email_h_c36ded_idx'), models.Index(fields=['created_at'], name='waitlist_en_created_6e5a63_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZKUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('username_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('encrypted_data', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('auth_proof', models.CharField(max_length=255, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of device fingerprint for one device per user', max_length=64, null=True, unique=True)),
                ('passkey_credential_id', models.CharField(blank=True, help_text='WebAuthn credential ID for biometric authentication', max_length=512, null=True)),
                ('passkey_public_key', models.TextField(blank=True, help_text='Public key for passkey verification (not used for ZK, stored for future verification)', null=True)),
                ('has_passkey', models.BooleanField(default=False, help_text='Whether user has registered a passkey')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether the user's email has been verified")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zero-Knowledge User',
                'verbose_name_plural': 'Zero-Knowledge Users',
                'db_table': 'zk_users',
                'indexes': [models.Index(fields=['auth_proof'], name='zk_users_auth_pr_733a27_idx'), models.Index(fields=['email_hash'], name='zk_users_email_h_cf2641_idx'), models.Index(fields=['username_hash'], name='zk_users_usernam_573b64_idx'), models.Index(fields=['passkey_credential_id'], name='zk_users_passkey_39de1f_idx'), models.Index(fields=['device_fingerprint'], name='zk_users_device__83ee14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZKTwoFactorLoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_data', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_method', models.CharField(choices=[('master_key', 'Master Key'), ('passkey', 'Passkey')], default='master_key', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_login_sessions', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': '2FA Login Session',
                'verbose_name_plural': '2FA Login Sessions',
                'db_table': 'zk_two_factor_login_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKTwoFactorAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totp_secret', models.CharField(help_text='TOTP secret key for generating codes', max_length=255)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is currently enabled')),
                ('backup_codes', models.TextField(blank=True, help_text='JSON array of backup codes (encrypted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'db_table': 'zk_two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='ZKRefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('auth_method', models.CharField(choices=[('master_key', 'Master Key'), ('passkey', 'Passkey')], default='master_key', max_length=20)),
                ('device_fingerprint', models.CharField(blank=True, help_text='SHA-256 hash of device fingerprint for session tracking', max_length=64, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'zk_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZKPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_salt', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'zk_password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
