# Generated by Django 5.2.7 on 2025-10-24 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zkpasswordresettoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Reset Token', 'verbose_name_plural': 'Password Reset Tokens'},
        ),
        migrations.AlterModelOptions(
            name='zkrefreshtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Refresh Token', 'verbose_name_plural': 'Refresh Tokens'},
        ),
        migrations.AlterModelOptions(
            name='zkuser',
            options={'verbose_name': 'Zero-Knowledge User', 'verbose_name_plural': 'Zero-Knowledge Users'},
        ),
        migrations.AddField(
            model_name='zkpasswordresettoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zkrefreshtoken',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zkrefreshtoken',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='username_hash',
            field=models.CharField(db_index=True, default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zkpasswordresettoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='zkuser',
            index=models.Index(fields=['username_hash'], name='zk_users_usernam_573b64_idx'),
        ),
        migrations.AlterModelTable(
            name='zkpasswordresettoken',
            table='zk_password_reset_tokens',
        ),
        migrations.AlterModelTable(
            name='zkrefreshtoken',
            table='zk_refresh_tokens',
        ),
    ]
