# Generated by Django 5.2.7 on 2025-10-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_zkpasswordresettoken_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkrefreshtoken',
            name='auth_method',
            field=models.CharField(choices=[('master_key', 'Master Key'), ('passkey', 'Passkey')], default='master_key', max_length=20),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='has_passkey',
            field=models.BooleanField(default=False, help_text='Whether user has registered a passkey'),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='passkey_credential_id',
            field=models.CharField(blank=True, help_text='WebAuthn credential ID for biometric authentication', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='passkey_public_key',
            field=models.TextField(blank=True, help_text='Public key for passkey verification (not used for ZK, stored for future verification)', null=True),
        ),
        migrations.AddIndex(
            model_name='zkuser',
            index=models.Index(fields=['passkey_credential_id'], name='zk_users_passkey_39de1f_idx'),
        ),
    ]
