# Generated by Django 5.2.7 on 2025-10-25 07:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_zkrefreshtoken_auth_method_zkuser_has_passkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False)),
                ('encrypted_data', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('auth_proof', models.CharField(max_length=255)),
                ('username_hash', models.CharField(max_length=64)),
                ('passkey_credential_id', models.CharField(blank=True, max_length=512, null=True)),
                ('passkey_public_key', models.TextField(blank=True, null=True)),
                ('use_both_methods', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'zk_email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='zkuser',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
        migrations.AlterField(
            model_name='zkuser',
            name='username_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='zkuser',
            index=models.Index(fields=['email_hash'], name='zk_users_email_h_cf2641_idx'),
        ),
    ]
