# Generated by Django 5.2.7 on 2025-10-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_zkemailverificationtoken_zkuser_email_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkemailverificationtoken',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 hash of device fingerprint for registration', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='zkrefreshtoken',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 hash of device fingerprint for session tracking', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='zkuser',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of device fingerprint for one device per user', max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='zkuser',
            index=models.Index(fields=['device_fingerprint'], name='zk_users_device__83ee14_idx'),
        ),
    ]
