# Generated by Django 5.2.8 on 2025-11-28 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_zkemailverificationtoken_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKTwoFactorAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totp_secret', models.CharField(help_text='TOTP secret key for generating codes', max_length=255)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether 2FA is currently enabled')),
                ('backup_codes', models.TextField(blank=True, help_text='JSON array of backup codes (encrypted)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Two-Factor Authentication',
                'verbose_name_plural': 'Two-Factor Authentications',
                'db_table': 'zk_two_factor_auth',
            },
        ),
    ]
