# Generated by Django 5.2.8 on 2025-11-28 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_zktwofactorauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKTwoFactorLoginSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('encrypted_data', models.TextField()),
                ('salt', models.CharField(max_length=255)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('auth_method', models.CharField(choices=[('master_key', 'Master Key'), ('passkey', 'Passkey')], default='master_key', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_login_sessions', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': '2FA Login Session',
                'verbose_name_plural': '2FA Login Sessions',
                'db_table': 'zk_two_factor_login_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
