# Generated by Django 5.2.8 on 2025-12-09 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_zktwofactorloginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_data', models.TextField(help_text='AES-256-GCM encrypted waitlist data (base64)')),
                ('salt', models.CharField(help_text='Cryptographic salt for key derivation (base64)', max_length=255)),
                ('email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of email for duplicate checking', max_length=64)),
                ('consent_to_updates', models.BooleanField(default=True, help_text='Whether user consented to receive updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'db_table': 'waitlist_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_hash'], name='waitlist_en_email_h_c36ded_idx'), models.Index(fields=['created_at'], name='waitlist_en_created_6e5a63_idx')],
            },
        ),
    ]
