# Generated by Django 5.2.8 on 2026-02-05 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_blocks', models.TextField(help_text='Encrypted JSON array of identity blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_canvas', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Identity Canvas',
                'verbose_name_plural': 'Identity Canvases',
                'db_table': 'identity_canvas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PANUniquenessProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (pan_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 5 characters of pan_hash for prefix matching', max_length=5)),
                ('pan_hash', models.CharField(db_index=True, help_text='SHA-256 hash of PAN number (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PAN Uniqueness Proof',
                'verbose_name_plural': 'PAN Uniqueness Proofs',
                'db_table': 'pan_uniqueness_proofs',
                'indexes': [models.Index(fields=['prefix'], name='pan_uniquen_prefix_d845f1_idx'), models.Index(fields=['final_hash'], name='pan_uniquen_final_h_712978_idx'), models.Index(fields=['pan_hash'], name='pan_uniquen_pan_has_fe21e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniquenessProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (aadhaar_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 5 characters of aadhaar_hash for prefix matching', max_length=5)),
                ('aadhaar_hash', models.CharField(db_index=True, help_text='SHA-256 hash of Aadhaar number (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uniqueness Proof',
                'verbose_name_plural': 'Uniqueness Proofs',
                'db_table': 'uniqueness_proofs',
                'indexes': [models.Index(fields=['prefix'], name='uniqueness__prefix_7d5ab9_idx'), models.Index(fields=['final_hash'], name='uniqueness__final_h_b421eb_idx'), models.Index(fields=['aadhaar_hash'], name='uniqueness__aadhaar_041843_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationCanvas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_blocks', models.TextField(help_text='Encrypted JSON array of verification blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_canvas', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Verification Canvas',
                'verbose_name_plural': 'Verification Canvases',
                'db_table': 'verification_canvas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AadhaarVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhaar_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the Aadhaar number', max_length=64)),
                ('aadhaar_hash_with_pepper', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of (Aadhaar number + PUBLIC_PEPPER) for uniqueness proof', max_length=64, null=True)),
                ('reference_id', models.CharField(help_text='Reference ID returned by Sandbox generate OTP API', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', help_text='Latest status from Sandbox', max_length=20)),
                ('sandbox_transaction_id', models.CharField(blank=True, help_text='Sandbox transaction identifier (if provided)', max_length=128, null=True)),
                ('sandbox_message', models.CharField(blank=True, help_text='Latest message from Sandbox', max_length=255, null=True)),
                ('sandbox_metadata', models.JSONField(blank=True, help_text='Sanitized metadata returned from Sandbox (no PII)', null=True)),
                ('simulated_otp', models.CharField(blank=True, help_text='DEV helper storing OTP when Sandbox is not configured', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User that initiated the Aadhaar OKYC flow', on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_kyc_sessions', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Aadhaar Verification Session',
                'verbose_name_plural': 'Aadhaar Verification Sessions',
                'db_table': 'aadhaar_verification_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='aadhaar_ver_user_id_68581d_idx'), models.Index(fields=['aadhaar_hash'], name='aadhaar_ver_aadhaar_da133b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of document being verified', max_length=50)),
                ('document_hash', models.CharField(db_index=True, help_text='SHA-256 hash of document identifier (e.g., PAN number, license number)', max_length=64)),
                ('verification_method', models.CharField(choices=[('manual_upload', 'Manual Upload'), ('third_party', 'Third Party API'), ('institutional', 'Institutional Verification')], help_text='Method used for verification', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_metadata', models.TextField(blank=True, help_text='Additional verification metadata (encrypted)', null=True)),
                ('user', models.ForeignKey(help_text='User requesting document verification', on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'db_table': 'document_verifications',
                'indexes': [models.Index(fields=['user', 'block_type', 'status'], name='document_ve_user_id_ef21b6_idx'), models.Index(fields=['document_hash', 'status'], name='document_ve_documen_146e65_idx')],
                'unique_together': {('user', 'block_type', 'document_hash')},
            },
        ),
        migrations.CreateModel(
            name='CanvasHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_blocks_snapshot', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, help_text='Action that created this version (create, update, delete)', max_length=50, null=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='identity_canvas.identitycanvas')),
            ],
            options={
                'verbose_name': 'Canvas History',
                'verbose_name_plural': 'Canvas Histories',
                'db_table': 'canvas_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['canvas', '-created_at'], name='canvas_hist_canvas__4144cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsernameProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (username_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 8 characters of username hash for prefix matching', max_length=8)),
                ('username_hash', models.CharField(db_index=True, help_text='SHA-256 hash of username (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this username', on_delete=django.db.models.deletion.CASCADE, related_name='username_proof', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Username Proof',
                'verbose_name_plural': 'Username Proofs',
                'db_table': 'username_proofs',
                'indexes': [models.Index(fields=['prefix'], name='username_pr_prefix_bcb6d4_idx'), models.Index(fields=['proof_hash'], name='username_pr_proof_h_a12004_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiableBlockOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of verifiable block (email, phone, etc.)', max_length=50)),
                ('value_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the value being verified (email, phone, etc.)', max_length=64)),
                ('otp_code', models.CharField(help_text='6-digit OTP code for verification', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP has been successfully verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification was completed', null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification_otps', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Verifiable Block OTP',
                'verbose_name_plural': 'Verifiable Block OTPs',
                'db_table': 'verifiable_block_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'block_type', 'is_verified'], name='verifiable__user_id_4e0afb_idx'), models.Index(fields=['value_hash', 'is_verified'], name='verifiable__value_h_d73cc9_idx'), models.Index(fields=['expires_at'], name='verifiable__expires_74b944_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationCanvasHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_blocks_snapshot', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, help_text='Action that created this version (create, update, delete)', max_length=50, null=True)),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='identity_canvas.verificationcanvas')),
            ],
            options={
                'verbose_name': 'Verification Canvas History',
                'verbose_name_plural': 'Verification Canvas Histories',
                'db_table': 'verification_canvas_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['canvas', '-created_at'], name='verificatio_canvas__cb4b4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of verifiable block', max_length=50)),
                ('value_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the verified value', max_length=64)),
                ('verified_at', models.DateTimeField(auto_now_add=True, help_text='When this block was verified')),
                ('verification_method', models.CharField(default='otp', help_text='Method used for verification', max_length=50)),
                ('user', models.ForeignKey(help_text='User who owns this verified block', on_delete=django.db.models.deletion.CASCADE, related_name='verified_blocks', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Verified Block',
                'verbose_name_plural': 'Verified Blocks',
                'db_table': 'verified_blocks',
                'indexes': [models.Index(fields=['user', 'block_type'], name='verified_bl_user_id_b35780_idx'), models.Index(fields=['value_hash'], name='verified_bl_value_h_961a7c_idx')],
                'unique_together': {('user', 'block_type', 'value_hash')},
            },
        ),
    ]
