# Generated by Django 5.2.7 on 2025-10-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_canvas', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='canvashistory',
            new_name='canvas_hist_canvas__4144cc_idx',
            old_name='canvas_his_canvas__idx',
        ),
    ]
