# Generated by Django 5.2.7 on 2025-10-31 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_zkemailverificationtoken_device_fingerprint_and_more'),
        ('identity_canvas', '0002_rename_canvas_his_canvas__idx_canvas_hist_canvas__4144cc_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiableBlockOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], help_text='Type of verifiable block (email, phone, etc.)', max_length=50)),
                ('value_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the value being verified (email, phone, etc.)', max_length=64)),
                ('otp_code', models.CharField(help_text='6-digit OTP code for verification', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='When this OTP expires')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this OTP has been successfully verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification was completed', null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification_otps', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Verifiable Block OTP',
                'verbose_name_plural': 'Verifiable Block OTPs',
                'db_table': 'verifiable_block_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'block_type', 'is_verified'], name='verifiable__user_id_4e0afb_idx'), models.Index(fields=['value_hash', 'is_verified'], name='verifiable__value_h_d73cc9_idx'), models.Index(fields=['expires_at'], name='verifiable__expires_74b944_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], help_text='Type of verifiable block', max_length=50)),
                ('value_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the verified value', max_length=64)),
                ('verified_at', models.DateTimeField(auto_now_add=True, help_text='When this block was verified')),
                ('verification_method', models.CharField(default='otp', help_text='Method used for verification', max_length=50)),
                ('user', models.ForeignKey(help_text='User who owns this verified block', on_delete=django.db.models.deletion.CASCADE, related_name='verified_blocks', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Verified Block',
                'verbose_name_plural': 'Verified Blocks',
                'db_table': 'verified_blocks',
                'indexes': [models.Index(fields=['user', 'block_type'], name='verified_bl_user_id_b35780_idx'), models.Index(fields=['value_hash'], name='verified_bl_value_h_961a7c_idx')],
                'unique_together': {('user', 'block_type', 'value_hash')},
            },
        ),
    ]
