# Generated by Django 5.2.7 on 2025-11-03 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_zkemailverificationtoken_device_fingerprint_and_more'),
        ('identity_canvas', '0003_verifiableblockotp_verifiedblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiableblockotp',
            name='block_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('identity_level_3', 'Identity Level 3'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('digilocker', 'DigiLocker Document')], help_text='Type of verifiable block (email, phone, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='verifiedblock',
            name='block_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('identity_level_3', 'Identity Level 3'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('digilocker', 'DigiLocker Document')], help_text='Type of verifiable block', max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('identity_level_3', 'Identity Level 3'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('digilocker', 'DigiLocker Document')], help_text='Type of document being verified', max_length=50)),
                ('document_hash', models.CharField(db_index=True, help_text='SHA-256 hash of document identifier (e.g., PAN number, license number)', max_length=64)),
                ('verification_method', models.CharField(choices=[('digilocker', 'DigiLocker'), ('manual_upload', 'Manual Upload'), ('third_party', 'Third Party API'), ('institutional', 'Institutional Verification')], help_text='Method used for verification', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('digilocker_access_token', models.TextField(blank=True, help_text='DigiLocker OAuth token (encrypted)', null=True)),
                ('digilocker_document_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('verification_metadata', models.TextField(blank=True, help_text='Additional verification metadata (encrypted)', null=True)),
                ('user', models.ForeignKey(help_text='User requesting document verification', on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'db_table': 'document_verifications',
                'indexes': [models.Index(fields=['user', 'block_type', 'status'], name='document_ve_user_id_ef21b6_idx'), models.Index(fields=['document_hash', 'status'], name='document_ve_documen_146e65_idx')],
                'unique_together': {('user', 'block_type', 'document_hash')},
            },
        ),
    ]
