# Generated by Django 5.2.7 on 2025-11-03 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_zkemailverificationtoken_device_fingerprint_and_more'),
        ('identity_canvas', '0004_alter_verifiableblockotp_block_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsernameProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (username_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 8 characters of username hash for prefix matching', max_length=8)),
                ('username_hash', models.CharField(db_index=True, help_text='SHA-256 hash of username (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User who owns this username', on_delete=django.db.models.deletion.CASCADE, related_name='username_proof', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Username Proof',
                'verbose_name_plural': 'Username Proofs',
                'db_table': 'username_proofs',
                'indexes': [models.Index(fields=['prefix'], name='username_pr_prefix_bcb6d4_idx'), models.Index(fields=['proof_hash'], name='username_pr_proof_h_a12004_idx')],
            },
        ),
    ]
