# Generated by Django 5.2.7 on 2025-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_canvas', '0005_usernameproof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentverification',
            name='digilocker_access_token',
        ),
        migrations.RemoveField(
            model_name='documentverification',
            name='digilocker_document_uri',
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='block_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of document being verified', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentverification',
            name='verification_method',
            field=models.CharField(choices=[('manual_upload', 'Manual Upload'), ('third_party', 'Third Party API'), ('institutional', 'Institutional Verification')], help_text='Method used for verification', max_length=50),
        ),
        migrations.AlterField(
            model_name='verifiableblockotp',
            name='block_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of verifiable block (email, phone, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='verifiedblock',
            name='block_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('pan_card', 'PAN Card'), ('crypto_wallet', 'Crypto Wallet'), ('education', 'Education'), ('employment', 'Employment'), ('professional_license', 'Professional License'), ('aadhar', 'Aadhaar Card'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID'), ('passport', 'Passport')], help_text='Type of verifiable block', max_length=50),
        ),
    ]
