# Generated by Django 5.2.8 on 2025-11-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_canvas', '0007_verificationcanvas'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationcanvashistory',
            new_name='verificatio_canvas__cb4b4b_idx',
            old_name='verification_canvas_hist_idx',
        ),
    ]
