# Generated by Django 5.2.8 on 2025-11-27 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_zkemailverificationtoken_device_fingerprint_and_more'),
        ('identity_canvas', '0008_rename_verification_canvas_hist_idx_verificatio_canvas__cb4b4b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadhaarVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhaar_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the Aadhaar number', max_length=64)),
                ('reference_id', models.CharField(help_text='Reference ID returned by Sandbox generate OTP API', max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', help_text='Latest status from Sandbox', max_length=20)),
                ('sandbox_transaction_id', models.CharField(blank=True, help_text='Sandbox transaction identifier (if provided)', max_length=128, null=True)),
                ('sandbox_message', models.CharField(blank=True, help_text='Latest message from Sandbox', max_length=255, null=True)),
                ('sandbox_metadata', models.JSONField(blank=True, help_text='Sanitized metadata returned from Sandbox (no PII)', null=True)),
                ('simulated_otp', models.CharField(blank=True, help_text='DEV helper storing OTP when Sandbox is not configured', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User that initiated the Aadhaar OKYC flow', on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_kyc_sessions', to='authentication.zkuser')),
            ],
            options={
                'verbose_name': 'Aadhaar Verification Session',
                'verbose_name_plural': 'Aadhaar Verification Sessions',
                'db_table': 'aadhaar_verification_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='aadhaar_ver_user_id_68581d_idx'), models.Index(fields=['aadhaar_hash'], name='aadhaar_ver_aadhaar_da133b_idx')],
            },
        ),
    ]
