# Generated by Django 5.2.8 on 2025-11-27 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_canvas', '0009_aadhaarverificationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarverificationsession',
            name='aadhaar_hash_with_pepper',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of (Aadhaar number + PUBLIC_PEPPER) for uniqueness proof', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UniquenessProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (aadhaar_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 5 characters of aadhaar_hash for prefix matching', max_length=5)),
                ('aadhaar_hash', models.CharField(db_index=True, help_text='SHA-256 hash of Aadhaar number (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uniqueness Proof',
                'verbose_name_plural': 'Uniqueness Proofs',
                'db_table': 'uniqueness_proofs',
                'indexes': [models.Index(fields=['prefix'], name='uniqueness__prefix_7d5ab9_idx'), models.Index(fields=['final_hash'], name='uniqueness__final_h_b421eb_idx'), models.Index(fields=['aadhaar_hash'], name='uniqueness__aadhaar_041843_idx')],
            },
        ),
    ]
