# Generated by Django 5.2.8 on 2025-11-27 20:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_canvas', '0010_aadhaarverificationsession_aadhaar_hash_with_pepper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PANUniquenessProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_hash', models.CharField(db_index=True, help_text='SHA-256 hash of (pan_hash + SECRET_PEPPER) for uniqueness proof', max_length=64, unique=True)),
                ('prefix', models.CharField(db_index=True, help_text='First 5 characters of pan_hash for prefix matching', max_length=5)),
                ('pan_hash', models.CharField(db_index=True, help_text='SHA-256 hash of PAN number (with public pepper) for prefix matching', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PAN Uniqueness Proof',
                'verbose_name_plural': 'PAN Uniqueness Proofs',
                'db_table': 'pan_uniqueness_proofs',
                'indexes': [models.Index(fields=['prefix'], name='pan_uniquen_prefix_d845f1_idx'), models.Index(fields=['final_hash'], name='pan_uniquen_final_h_712978_idx'), models.Index(fields=['pan_hash'], name='pan_uniquen_pan_has_fe21e6_idx')],
            },
        ),
    ]
